In [1]:
 import numpy.random as rd

In [2]:
rd

<module 'numpy.random' from 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [3]:
array = rd.randint(1,3,16)

In [4]:
array

array([1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1])

In [13]:
array = array.reshape(4,4)

In [14]:
array

array([[1, 2, 1, 2],
       [2, 1, 2, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 1]])

In [15]:
array + array

array([[2, 4, 2, 4],
       [4, 2, 4, 2],
       [4, 4, 4, 4],
       [4, 4, 4, 2]])

In [16]:
array * array

array([[1, 4, 1, 4],
       [4, 1, 4, 1],
       [4, 4, 4, 4],
       [4, 4, 4, 1]])

In [17]:
1 / array

array([[1. , 0.5, 1. , 0.5],
       [0.5, 1. , 0.5, 1. ],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 1. ]])

In [18]:
1 // array #yuvarlama yapıyor.

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 1]], dtype=int32)

In [20]:
array ** 3 #herbirdeğerinüstünü alıyor

array([[1, 8, 1, 8],
       [8, 1, 8, 1],
       [8, 8, 8, 8],
       [8, 8, 8, 1]], dtype=int32)