In [1]:
import numpy as np

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
array = np.ones((2,3))
array


array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
array.astype(int)

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
np.eye(3,3)*4

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(12,26,2)

array([12, 14, 16, 18, 20, 22, 24])

In [8]:
np.linspace(2,4,9)

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  ])

In [9]:
import numpy.random as rd

In [10]:
rd.rand(5)

array([0.87369609, 0.30672542, 0.15096547, 0.36617405, 0.23977582])

In [11]:
arr  = rd.randint(0,10,15).reshape(3,5)

In [12]:
arr

array([[4, 7, 0, 1, 3],
       [5, 1, 8, 6, 3],
       [1, 2, 9, 1, 9]])

In [13]:
arr**2

array([[16, 49,  0,  1,  9],
       [25,  1, 64, 36,  9],
       [ 1,  4, 81,  1, 81]], dtype=int32)

In [16]:
arr_cop = arr[-2:].copy

In [17]:
arr_copy

NameError: name 'arr_copy' is not defined