In [1]:
import numpy.random as rd

In [2]:
rd

<module 'numpy.random' from 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [4]:
rd.rand(5)

array([0.91642743, 0.73158797, 0.65773286, 0.64831008, 0.97342638])

In [5]:
rd.randint(1,6,5) #1 ile 6 arasında 5 tane rastgele sayı

array([2, 2, 4, 3, 5])

In [6]:
rd.randn(10)

array([-1.62458612, -0.05790618,  0.17274076,  0.68204599,  0.88813143,
       -0.55721807, -1.1975011 ,  0.66996744,  0.86743506, -1.05839638])

In [7]:
array = rd.randint(2,5,10)

In [8]:
array

array([2, 2, 3, 4, 4, 4, 3, 2, 2, 4])

In [9]:
array.reshape(5,2)

array([[2, 2],
       [3, 4],
       [4, 4],
       [3, 2],
       [2, 4]])