In [1]:
import numpy as np


In [2]:
list1 = [0,1,2,3]
list1

[0, 1, 2, 3]

In [3]:
array = np.array(list1)

In [4]:
array

array([0, 1, 2, 3])

In [5]:
list2 = [10,11,12,13]

In [6]:
kom_list = [list1,list2]

In [8]:
kom_list

[[0, 1, 2, 3], [10, 11, 12, 13]]

In [9]:
kom_array = np.array (kom_list)
kom_array

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [10]:
kom_array.dtype

dtype('int32')

In [12]:
np.array(kom_list,dtype='float')

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.]])

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
sifir = np.zeros((5,2))

In [15]:
sifir

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
sifir.astype('int')

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.empty((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(5,10,2)

array([5, 7, 9])

In [25]:
np.linspace(0,5,11) #0 la 5 arasını 11 eşit parçaya böldük.

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])