In [1]:
import numpy as np

In [4]:
array = np.arange(12)

In [5]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
array[1]

1

In [7]:
array[-1] #arraydeki son değer

11

In [8]:
array[0:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
array[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [12]:
array[6:-1:2] #6dan son degere kadar 2şer

array([ 6,  8, 10])

In [13]:
array[6::2] #2.yöntem

array([ 6,  8, 10])

In [16]:
array[6:11:2] #3.yöntem

array([ 6,  8, 10])

In [17]:
array[0:4] = 11

In [18]:
array

array([11, 11, 11, 11,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
array  =np.arange(12)

In [21]:
parca_array = array[0:6]

In [22]:
parca_array

array([0, 1, 2, 3, 4, 5])

In [23]:
parca_array[:] = 4

In [24]:
parca_array

array([4, 4, 4, 4, 4, 4])

In [25]:
array

array([ 4,  4,  4,  4,  4,  4,  6,  7,  8,  9, 10, 11])

In [33]:
copy_array = array[0:6].copy()

In [34]:
copy_array

array([3, 3, 3, 3, 3, 3])

In [35]:
parca_array[:] = 3

In [36]:
array

array([ 3,  3,  3,  3,  3,  3,  6,  7,  8,  9, 10, 11])

In [37]:
copy_array2 = array[0:3].copy()

In [40]:
copy_array2

array([4, 4, 4])

In [39]:
copy_array2[:] = 4

In [41]:
array

array([ 3,  3,  3,  3,  3,  3,  6,  7,  8,  9, 10, 11])

In [44]:
array_2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
array_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
array_2d[0]

array([0, 1, 2])

In [46]:
array_2d[2][2]

8

In [47]:
array_2d[2,2]

8

In [48]:
array_2d[1:,1:]

array([[4, 5],
       [7, 8]])

In [49]:
array_2d[:2,:2]

array([[0, 1],
       [3, 4]])

In [52]:
array_2d = np.arange(25).reshape(5,5)

In [53]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
array_2d[[0,2]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [55]:
array_2d[:,[1,4]]

array([[ 1,  4],
       [ 6,  9],
       [11, 14],
       [16, 19],
       [21, 24]])

In [56]:
array

array([ 3,  3,  3,  3,  3,  3,  6,  7,  8,  9, 10, 11])

In [57]:
array>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [58]:
array[array>5] #degerlerini yazdırır.

array([ 6,  7,  8,  9, 10, 11])