In [1]:
import numpy as np

In [2]:
array = np.arange(12).reshape(6,2)

In [3]:
array

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
array.sum()

66

In [5]:
array.sum(axis=0) #satır boyunca

array([30, 36])

In [6]:
array.sum(axis=1) #sutunboyunca

array([ 1,  5,  9, 13, 17, 21])

In [7]:
array.max()

11

In [8]:
array.max(axis=0) #satır boyunca max degerleri

array([10, 11])

In [9]:
array.argmax(axis=0) #max degere tekabuleden ındex numarası

array([5, 5], dtype=int64)

In [10]:
array.min(axis=1)#sutun boyunca 

array([ 0,  2,  4,  6,  8, 10])

In [11]:
array.var()

11.916666666666666

In [12]:
array.std()

3.452052529534663

In [13]:
array.mean(axis=1)

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5])

In [14]:
import numpy.random as rd

In [16]:
sort_array = rd.rand(12).reshape(4,3)
sort_array

array([[0.9783765 , 0.24843213, 0.63190638],
       [0.17878826, 0.53618876, 0.42635796],
       [0.54177944, 0.73845372, 0.22375324],
       [0.33684484, 0.4437317 , 0.20846265]])

In [18]:
sort_array.sort(axis=1)
              

In [19]:
sort_array.sort(axis=0)
sort_array

array([[0.17878826, 0.33684484, 0.4437317 ],
       [0.20846265, 0.42635796, 0.53618876],
       [0.22375324, 0.54177944, 0.73845372],
       [0.24843213, 0.63190638, 0.9783765 ]])

In [23]:
sehir = np.array(['Adana','İzmir','İstanbul','Adana'])
sehir

array(['Adana', 'İzmir', 'İstanbul', 'Adana'], dtype='<U8')

In [21]:
sehir.sort()

In [22]:
sehir

array(['Adana', 'İstanbul', 'İzmir'], dtype='<U8')

In [25]:
np.unique(sehir)

array(['Adana', 'İstanbul', 'İzmir'], dtype='<U8')

In [26]:
np.in1d('Afyon',sehir)

array([False])

In [27]:
array.shape

(6, 2)

In [28]:
array.shape[0]#satır degeri

6

In [29]:
mantik = np.array([True,False,True,False])
mantik

array([ True, False,  True, False])

In [31]:
mantik.any() #herhangi bir deger dogru ise

True

In [32]:
mantik.all() #tüm degerler dogru olması gerekiyor

False